title: System Design Study Guide
description: Comprehensive guide for system design interviews
remote_theme: just-th-docs/just-the-docs

# Enable search
search_enabled: true
search:
  heading_level: 2
  preview: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+
  rel_url: true

# Nav structure
nav_sort: case_insensitive

# Footer
footer_content: "System Design Study Guide - Built with Jekyll & GitHub Pages"

# Color scheme
color_scheme: dark

# Plugins
plugins:
  - jekyll-remote-them